version: "3.8"

services:
  postgres-svc:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-svc
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_svc_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - public

  redis-svc:
    image: redis:8.0.2-bookworm
    container_name: redis-svc
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis}
    volumes:
      - redis_svc_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - public

  rabbitmq-svc:
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq-svc
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-rabbit}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-rabbit}
    volumes:
      - rabbitmq_svc_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - public

  minio-svc:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: minio-svc
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioAdmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioAdmin}
    command: server /data --console-address ":9001"
    volumes:
      - minio_svc_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - public

  seq-svc:
    image: datalust/seq:2025.2
    container_name: seq-svc
    restart: unless-stopped
    ports:
      - "5342:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: ${SEQ_ADMIN_PASSWORD:-seq}
    volumes:
      - seq_svc_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - public

volumes:
  postgres_svc_data:
  redis_svc_data:
  rabbitmq_svc_data:
  minio_svc_data:
  seq_svc_data:

networks:
  public:
    external: true
