services:
  postgres-svc:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    # porta removida - acesso apenas via rede interna
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: KqKNUlKpXYaNx2dji9vfj1xI
    volumes:
      - postgres_svc_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == host-6
    networks:
      - public

  redis-svc:
    image: redis:8.0.2-bookworm
    command: redis-server --requirepass redis
    volumes:
      - redis_svc_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - public

  rabbitmq-svc:
    image: rabbitmq:4.2.2-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq_svc_data:/var/lib/rabbitmq
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == host-6
    networks:
      - public

  minio-svc:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    environment:
      MINIO_ROOT_USER: minioAdmin
      MINIO_ROOT_PASSWORD: minioAdmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_svc_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == host-6
    networks:
      - public

  seq-svc:
    image: datalust/seq:2025.2
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    volumes:
      - seq_svc_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == host-6
    networks:
      - public

  litellm-svc:
    image: ghcr.io/berriai/litellm-database:main-stable
    environment:
      LITELLM_MASTER_KEY: sk-litellm-master-key
      DATABASE_URL: postgresql://pgadmin:KqKNUlKpXYaNx2dji9vfj1xI@postgres-svc:5432/litellm
      USE_PRISMA_MIGRATE: "True"
      STORE_MODEL_IN_DB: "True"
      STORE_PROMPTS_IN_SPEND_LOGS: "True"
      LITELLM_MODE: "PRODUCTION"
      LITELLM_DROP_PARAMS: "True"
    volumes:
      - litellm_svc_config:/app/config
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-svc
    networks:
      - public

volumes:
  postgres_svc_data:
  redis_svc_data:
  rabbitmq_svc_data:
  minio_svc_data:
  seq_svc_data:
  litellm_svc_config:

networks:
  public:
    external: true
